/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddRecipe: typeof import('./src/components/AddRecipe.vue')['default']
    HorizontalSlide: typeof import('./src/components/HorizontalSlide.vue')['default']
    PostRecipe: typeof import('./src/components/PostRecipe.vue')['default']
    RecipeCard: typeof import('./src/components/RecipeCard.vue')['default']
    RecipeDetail: typeof import('./src/components/RecipeDetail.vue')['default']
    RecipeList: typeof import('./src/components/RecipeList.vue')['default']
    RecipeTop: typeof import('./src/components/RecipeTop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResults: typeof import('./src/components/SearchResults.vue')['default']
    SupabaseImage: typeof import('./src/components/SupabaseImage.vue')['default']
    UploadPhoto: typeof import('./src/components/UploadPhoto.vue')['default']
    VerticalSlide: typeof import('./src/components/VerticalSlide.vue')['default']
  }
}
